Repository NetoECommerce/Skeletal, pull requests merged in 2018-04, with the labels that each got.

#320 Updating 'category:' to 'filter_category:'
  src/templates/cms/home.template.html
Labels: shoulder check

#322 Review forms changes
  src/templates/customer/write_contentreview/confirm.template.html
  src/templates/customer/write_contentreview/not_found.template.html
  src/templates/customer/write_review/not_found.template.html
  src/templates/customer/write_review/preview.template.html
  src/templates/customer/write_review/template.html
  src/templates/customer/write_review/write.template.html
Labels: question

#332 Added required attribute to required login/register fields
  src/templates/customer/login.template.html
  src/templates/customer/register/template.html
Labels: shoulder check

#379 Approve quote button wants to be noticed
  src/templates/customer/template.html
Labels: shoulder check

#384 Fixed css to use correct classes
  src/templates/customer/forgotpwd/template.html
  src/templates/customer/mystore/view.template.html
  src/templates/customer/standing_orders/template.html
  src/templates/customer/write_contentreview/preview.template.html
Labels: shoulder check

#349 Added "shipping not available" alert to cart page
  src/templates/cart/shopping_cart.template.html
  src/templates/products/includes/buying_options.template.html
Labels: shoulder check

#293 Display Out of Stock for relevant SKUs by default
  src/templates/products/includes/child_products.template.html
Labels: enhancement, shoulder check

#334 Decrease z-index on cart button
  src/css/app.css
  src/css/less/_neto.less
Labels: shoulder check
