Repository NetoECommerce/Skeletal, pull requests merged in 2018-03, with the labels that each got.

#350 Forking skeletal
  README.md
Labels: enhancement

#365 Simplify product template
  src/templates/products/includes/child_products.template.html
  src/templates/products/includes/components.template.html
  src/templates/products/includes/product_information.template.html
  src/templates/products/includes/product_scripts.template.html
  src/templates/products/template.html
Labels: enhancement, shoulder check

#357 Added text-align: right to savings container
  src/css/app.css
  src/css/less/_neto.less
Labels: shoulder check

#358 Revamp view order and quote pages
  src/templates/customer/nr_view_order/order.template.html
  src/templates/customer/nr_view_order/quote.template.html
  src/templates/customer/view_order/order.template.html
  src/templates/customer/view_order/quote.template.html
Labels: shoulder check

#354 Hide product page shipping calculator for service items
  src/templates/products/includes/buying_options.template.html
Labels: shoulder check

#369 UAT-68 email address is not required field
  src/templates/customer/forgotpwd/template.html
Labels: shoulder check
