Repository NetoECommerce/Skeletal, pull requests merged in 2018-05, with the labels that each got.

#403 Removed meta image tag
  src/templates/products/includes/images.template.html
Labels: shoulder check, v3

#402 fontawesome 5
  src/js/custom.js
  src/templates/cart/includes/cart_items.template.html
  src/templates/cart/includes/voucher_msg.template.html
  src/templates/cart/invoice.template.html
  src/templates/cart/shopping_cart.template.html
  src/templates/cms/default.template.html
  src/templates/cms/includes/sidebar.template.html
  src/templates/cms/store_finder.template.html
  src/templates/customer/nr_track_order/order.template.html
  src/templates/customer/template.html
  src/templates/customer/warranty/dispute_sent.template.html
  src/templates/customer/warranty/open_dispute.template.html
  src/templates/customer/warranty/select_dispute_reason.template.html
  src/templates/customer/warranty/select_dispute_type.template.html
  src/templates/customer/warranty/view_dispute.template.html
  src/templates/customer/wishlist/template.html
  src/templates/customer/write_review/preview.template.html
  src/templates/customer/write_review/write.template.html
  src/templates/footers/template.html
  src/templates/headers/includes/head.template.html
  src/templates/headers/template.html
  src/templates/products/includes/buying_options.template.html
  src/templates/products/includes/header.template.html
  src/templates/products/includes/product_information.template.html
  src/templates/stockists/template.html
  src/templates/thumbs/content/template.html
Labels: enhancement, shoulder check, v4

#316 Pre order stock investigation
  src/templates/products/includes/buying_options.template.html
  src/templates/products/includes/child_products.template.html
  src/templates/products/includes/components.template.html
  src/templates/products/includes/header.template.html
  src/templates/thumbs/product/list.template.html
  src/templates/thumbs/product/template.html
Labels: question, tested, v4

#408 Min on shipping calculator
  src/templates/products/includes/buying_options.template.html
Labels: PR Pending

#383 Notify Me button does not show loading animation on variation switch
  src/js/custom.js
  src/templates/products/includes/buying_options.template.html
  src/templates/products/includes/product_scripts.template.html
Labels: shoulder check, v3

#404 Add surcharge row to cart pricing information
  src/templates/cart/shopping_cart.template.html
Labels: shoulder check, v3

#406 Preload styles for modern browsers
  src/templates/headers/includes/head.template.html
  src/templates/headers/template.html
Labels: enhancement, v4

#398 Broken functionality on email address contains '+' character
  src/templates/cart/invoice.template.html
  src/templates/cart/rental_invoice.template.html
  src/templates/customer/approve_quote/accept_quote_confirm.template.html
  src/templates/customer/approve_quote/delete_quote_confirm.template.html
  src/templates/customer/approve_quote/template.html
Labels: bug, shoulder check, v3

#409 GDPR update
  src/js/custom.js
  src/templates/cart/onepage.template.html
  src/templates/customer/login.template.html
  src/templates/customer/register/template.html
  src/templates/customer/wholesaleregister/template.html
  src/templates/footers/template.html
  src/templates/products/includes/buying_options.template.html
Labels: enhancement, v3
