Repository NetoECommerce/Skeletal, pull requests merged in 2018-02, with the labels that each got.

#341 Issue 271
  src/templates/customer/wholesaleregister/template.html
Labels: shoulder check

#307 Updated availability schema on product header template
  src/templates/products/includes/header.template.html
Labels: enhancement, shoulder check

#340 PCI-297 update wording for new customer forgot password workflow and fix XSS
  src/templates/customer/forgotpwd/done.template.html
Labels: shoulder check

#331 Updated less to use partials
  gulpfile.js
  package-lock.json
  src/css/less/_custom.less
  src/css/less/_neto.less
  src/css/less/_variables.less
  src/css/less/app.less
Labels: enhancement, tested

#325 Moved required code in header/footer into their own files
  src/templates/footers/checkout.template.html
  src/templates/footers/includes/scripts.template.html
  src/templates/footers/template.html
  src/templates/headers/checkout.template.html
  src/templates/headers/empty.template.html
  src/templates/headers/includes/head.template.html
  src/templates/headers/template.html
Labels: tested

#286 fixed kit component price logic
  src/templates/products/includes/components.template.html
Labels: in progress
